In [1]:
import numpy as np

In [2]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

数组，相同数量 相同元素

array（）- returns a data structure in the NumPy array format

In [3]:
a.shape

(2, 4)

2行4列

In [4]:
a[1,2]

6

In [5]:
# 修改数组
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [6]:
a[1]

array([4, 5, 8, 7])

In [7]:
b = np.array([3,5])
b

array([3, 5])